/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignuprecruiteremailRouteImport } from './routes/signuprecruiteremail'
import { Route as SignuprecruiterRouteImport } from './routes/signuprecruiter'
import { Route as SignupdeveloperemailRouteImport } from './routes/signupdeveloperemail'
import { Route as SignupdeveloperRouteImport } from './routes/signupdeveloper'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ProfileeditRouteImport } from './routes/profileedit'
import { Route as PortfoliopageeditorRouteImport } from './routes/portfoliopageeditor'
import { Route as Portfoliodetailpage3RouteImport } from './routes/portfoliodetailpage3'
import { Route as Portfoliodetailpage2RouteImport } from './routes/portfoliodetailpage2'
import { Route as PortfoliodetailRouteImport } from './routes/portfoliodetail'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyprojectsRouteImport } from './routes/myprojects'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MyRouteImport } from './routes/my'
import { Route as ModifyportfolioRouteImport } from './routes/modifyportfolio'
import { Route as ModifyhackathonRouteImport } from './routes/modifyhackathon'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MergercreateportfolioRouteImport } from './routes/mergercreateportfolio'
import { Route as MemberselectionRouteImport } from './routes/memberselection'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HackathondetailRouteImport } from './routes/hackathondetail'
import { Route as HackathonRouteImport } from './routes/hackathon'
import { Route as CreateportfolioRouteImport } from './routes/createportfolio'
import { Route as CreatehackathonRouteImport } from './routes/createhackathon'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as TemplatesIdRouteImport } from './routes/templates.$id'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as MessagesNewRouteImport } from './routes/messages.new'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignuprecruiteremailRoute = SignuprecruiteremailRouteImport.update({
  id: '/signuprecruiteremail',
  path: '/signuprecruiteremail',
  getParentRoute: () => rootRouteImport,
} as any)
const SignuprecruiterRoute = SignuprecruiterRouteImport.update({
  id: '/signuprecruiter',
  path: '/signuprecruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupdeveloperemailRoute = SignupdeveloperemailRouteImport.update({
  id: '/signupdeveloperemail',
  path: '/signupdeveloperemail',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupdeveloperRoute = SignupdeveloperRouteImport.update({
  id: '/signupdeveloper',
  path: '/signupdeveloper',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileeditRoute = ProfileeditRouteImport.update({
  id: '/profileedit',
  path: '/profileedit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliopageeditorRoute = PortfoliopageeditorRouteImport.update({
  id: '/portfoliopageeditor',
  path: '/portfoliopageeditor',
  getParentRoute: () => rootRouteImport,
} as any)
const Portfoliodetailpage3Route = Portfoliodetailpage3RouteImport.update({
  id: '/portfoliodetailpage3',
  path: '/portfoliodetailpage3',
  getParentRoute: () => rootRouteImport,
} as any)
const Portfoliodetailpage2Route = Portfoliodetailpage2RouteImport.update({
  id: '/portfoliodetailpage2',
  path: '/portfoliodetailpage2',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliodetailRoute = PortfoliodetailRouteImport.update({
  id: '/portfoliodetail',
  path: '/portfoliodetail',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyprojectsRoute = MyprojectsRouteImport.update({
  id: '/myprojects',
  path: '/myprojects',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ModifyportfolioRoute = ModifyportfolioRouteImport.update({
  id: '/modifyportfolio',
  path: '/modifyportfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ModifyhackathonRoute = ModifyhackathonRouteImport.update({
  id: '/modifyhackathon',
  path: '/modifyhackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MergercreateportfolioRoute = MergercreateportfolioRouteImport.update({
  id: '/mergercreateportfolio',
  path: '/mergercreateportfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberselectionRoute = MemberselectionRouteImport.update({
  id: '/memberselection',
  path: '/memberselection',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathondetailRoute = HackathondetailRouteImport.update({
  id: '/hackathondetail',
  path: '/hackathondetail',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonRoute = HackathonRouteImport.update({
  id: '/hackathon',
  path: '/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateportfolioRoute = CreateportfolioRouteImport.update({
  id: '/createportfolio',
  path: '/createportfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatehackathonRoute = CreatehackathonRouteImport.update({
  id: '/createhackathon',
  path: '/createhackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TemplatesRoute,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfolioRoute,
} as any)
const MessagesNewRoute = MessagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contests': typeof ContestsRoute
  '/createhackathon': typeof CreatehackathonRoute
  '/createportfolio': typeof CreateportfolioRoute
  '/hackathon': typeof HackathonRoute
  '/hackathondetail': typeof HackathondetailRoute
  '/login': typeof LoginRoute
  '/memberselection': typeof MemberselectionRoute
  '/mergercreateportfolio': typeof MergercreateportfolioRoute
  '/messages': typeof MessagesRouteWithChildren
  '/modifyhackathon': typeof ModifyhackathonRoute
  '/modifyportfolio': typeof ModifyportfolioRoute
  '/my': typeof MyRoute
  '/mypage': typeof MypageRoute
  '/myprojects': typeof MyprojectsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfoliodetail': typeof PortfoliodetailRoute
  '/portfoliodetailpage2': typeof Portfoliodetailpage2Route
  '/portfoliodetailpage3': typeof Portfoliodetailpage3Route
  '/portfoliopageeditor': typeof PortfoliopageeditorRoute
  '/profileedit': typeof ProfileeditRoute
  '/recruiter': typeof RecruiterRoute
  '/signupdeveloper': typeof SignupdeveloperRoute
  '/signupdeveloperemail': typeof SignupdeveloperemailRoute
  '/signuprecruiter': typeof SignuprecruiterRoute
  '/signuprecruiteremail': typeof SignuprecruiteremailRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contests': typeof ContestsRoute
  '/createhackathon': typeof CreatehackathonRoute
  '/createportfolio': typeof CreateportfolioRoute
  '/hackathon': typeof HackathonRoute
  '/hackathondetail': typeof HackathondetailRoute
  '/login': typeof LoginRoute
  '/memberselection': typeof MemberselectionRoute
  '/mergercreateportfolio': typeof MergercreateportfolioRoute
  '/messages': typeof MessagesRouteWithChildren
  '/modifyhackathon': typeof ModifyhackathonRoute
  '/modifyportfolio': typeof ModifyportfolioRoute
  '/my': typeof MyRoute
  '/mypage': typeof MypageRoute
  '/myprojects': typeof MyprojectsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfoliodetail': typeof PortfoliodetailRoute
  '/portfoliodetailpage2': typeof Portfoliodetailpage2Route
  '/portfoliodetailpage3': typeof Portfoliodetailpage3Route
  '/portfoliopageeditor': typeof PortfoliopageeditorRoute
  '/profileedit': typeof ProfileeditRoute
  '/recruiter': typeof RecruiterRoute
  '/signupdeveloper': typeof SignupdeveloperRoute
  '/signupdeveloperemail': typeof SignupdeveloperemailRoute
  '/signuprecruiter': typeof SignuprecruiterRoute
  '/signuprecruiteremail': typeof SignuprecruiteremailRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contests': typeof ContestsRoute
  '/createhackathon': typeof CreatehackathonRoute
  '/createportfolio': typeof CreateportfolioRoute
  '/hackathon': typeof HackathonRoute
  '/hackathondetail': typeof HackathondetailRoute
  '/login': typeof LoginRoute
  '/memberselection': typeof MemberselectionRoute
  '/mergercreateportfolio': typeof MergercreateportfolioRoute
  '/messages': typeof MessagesRouteWithChildren
  '/modifyhackathon': typeof ModifyhackathonRoute
  '/modifyportfolio': typeof ModifyportfolioRoute
  '/my': typeof MyRoute
  '/mypage': typeof MypageRoute
  '/myprojects': typeof MyprojectsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfoliodetail': typeof PortfoliodetailRoute
  '/portfoliodetailpage2': typeof Portfoliodetailpage2Route
  '/portfoliodetailpage3': typeof Portfoliodetailpage3Route
  '/portfoliopageeditor': typeof PortfoliopageeditorRoute
  '/profileedit': typeof ProfileeditRoute
  '/recruiter': typeof RecruiterRoute
  '/signupdeveloper': typeof SignupdeveloperRoute
  '/signupdeveloperemail': typeof SignupdeveloperemailRoute
  '/signuprecruiter': typeof SignuprecruiterRoute
  '/signuprecruiteremail': typeof SignuprecruiteremailRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contests'
    | '/createhackathon'
    | '/createportfolio'
    | '/hackathon'
    | '/hackathondetail'
    | '/login'
    | '/memberselection'
    | '/mergercreateportfolio'
    | '/messages'
    | '/modifyhackathon'
    | '/modifyportfolio'
    | '/my'
    | '/mypage'
    | '/myprojects'
    | '/notifications'
    | '/onboarding'
    | '/portfolio'
    | '/portfoliodetail'
    | '/portfoliodetailpage2'
    | '/portfoliodetailpage3'
    | '/portfoliopageeditor'
    | '/profileedit'
    | '/recruiter'
    | '/signupdeveloper'
    | '/signupdeveloperemail'
    | '/signuprecruiter'
    | '/signuprecruiteremail'
    | '/templates'
    | '/jobs/$id'
    | '/messages/$id'
    | '/messages/new'
    | '/portfolio/$id'
    | '/templates/$id'
    | '/portfolio/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contests'
    | '/createhackathon'
    | '/createportfolio'
    | '/hackathon'
    | '/hackathondetail'
    | '/login'
    | '/memberselection'
    | '/mergercreateportfolio'
    | '/messages'
    | '/modifyhackathon'
    | '/modifyportfolio'
    | '/my'
    | '/mypage'
    | '/myprojects'
    | '/notifications'
    | '/onboarding'
    | '/portfoliodetail'
    | '/portfoliodetailpage2'
    | '/portfoliodetailpage3'
    | '/portfoliopageeditor'
    | '/profileedit'
    | '/recruiter'
    | '/signupdeveloper'
    | '/signupdeveloperemail'
    | '/signuprecruiter'
    | '/signuprecruiteremail'
    | '/jobs/$id'
    | '/messages/$id'
    | '/messages/new'
    | '/portfolio/$id'
    | '/templates/$id'
    | '/portfolio'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/contests'
    | '/createhackathon'
    | '/createportfolio'
    | '/hackathon'
    | '/hackathondetail'
    | '/login'
    | '/memberselection'
    | '/mergercreateportfolio'
    | '/messages'
    | '/modifyhackathon'
    | '/modifyportfolio'
    | '/my'
    | '/mypage'
    | '/myprojects'
    | '/notifications'
    | '/onboarding'
    | '/portfolio'
    | '/portfoliodetail'
    | '/portfoliodetailpage2'
    | '/portfoliodetailpage3'
    | '/portfoliopageeditor'
    | '/profileedit'
    | '/recruiter'
    | '/signupdeveloper'
    | '/signupdeveloperemail'
    | '/signuprecruiter'
    | '/signuprecruiteremail'
    | '/templates'
    | '/jobs/$id'
    | '/messages/$id'
    | '/messages/new'
    | '/portfolio/$id'
    | '/templates/$id'
    | '/portfolio/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ContestsRoute: typeof ContestsRoute
  CreatehackathonRoute: typeof CreatehackathonRoute
  CreateportfolioRoute: typeof CreateportfolioRoute
  HackathonRoute: typeof HackathonRoute
  HackathondetailRoute: typeof HackathondetailRoute
  LoginRoute: typeof LoginRoute
  MemberselectionRoute: typeof MemberselectionRoute
  MergercreateportfolioRoute: typeof MergercreateportfolioRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ModifyhackathonRoute: typeof ModifyhackathonRoute
  ModifyportfolioRoute: typeof ModifyportfolioRoute
  MyRoute: typeof MyRoute
  MypageRoute: typeof MypageRoute
  MyprojectsRoute: typeof MyprojectsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PortfoliodetailRoute: typeof PortfoliodetailRoute
  Portfoliodetailpage2Route: typeof Portfoliodetailpage2Route
  Portfoliodetailpage3Route: typeof Portfoliodetailpage3Route
  PortfoliopageeditorRoute: typeof PortfoliopageeditorRoute
  ProfileeditRoute: typeof ProfileeditRoute
  RecruiterRoute: typeof RecruiterRoute
  SignupdeveloperRoute: typeof SignupdeveloperRoute
  SignupdeveloperemailRoute: typeof SignupdeveloperemailRoute
  SignuprecruiterRoute: typeof SignuprecruiterRoute
  SignuprecruiteremailRoute: typeof SignuprecruiteremailRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signuprecruiteremail': {
      id: '/signuprecruiteremail'
      path: '/signuprecruiteremail'
      fullPath: '/signuprecruiteremail'
      preLoaderRoute: typeof SignuprecruiteremailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signuprecruiter': {
      id: '/signuprecruiter'
      path: '/signuprecruiter'
      fullPath: '/signuprecruiter'
      preLoaderRoute: typeof SignuprecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signupdeveloperemail': {
      id: '/signupdeveloperemail'
      path: '/signupdeveloperemail'
      fullPath: '/signupdeveloperemail'
      preLoaderRoute: typeof SignupdeveloperemailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signupdeveloper': {
      id: '/signupdeveloper'
      path: '/signupdeveloper'
      fullPath: '/signupdeveloper'
      preLoaderRoute: typeof SignupdeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profileedit': {
      id: '/profileedit'
      path: '/profileedit'
      fullPath: '/profileedit'
      preLoaderRoute: typeof ProfileeditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoliopageeditor': {
      id: '/portfoliopageeditor'
      path: '/portfoliopageeditor'
      fullPath: '/portfoliopageeditor'
      preLoaderRoute: typeof PortfoliopageeditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoliodetailpage3': {
      id: '/portfoliodetailpage3'
      path: '/portfoliodetailpage3'
      fullPath: '/portfoliodetailpage3'
      preLoaderRoute: typeof Portfoliodetailpage3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoliodetailpage2': {
      id: '/portfoliodetailpage2'
      path: '/portfoliodetailpage2'
      fullPath: '/portfoliodetailpage2'
      preLoaderRoute: typeof Portfoliodetailpage2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoliodetail': {
      id: '/portfoliodetail'
      path: '/portfoliodetail'
      fullPath: '/portfoliodetail'
      preLoaderRoute: typeof PortfoliodetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myprojects': {
      id: '/myprojects'
      path: '/myprojects'
      fullPath: '/myprojects'
      preLoaderRoute: typeof MyprojectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modifyportfolio': {
      id: '/modifyportfolio'
      path: '/modifyportfolio'
      fullPath: '/modifyportfolio'
      preLoaderRoute: typeof ModifyportfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modifyhackathon': {
      id: '/modifyhackathon'
      path: '/modifyhackathon'
      fullPath: '/modifyhackathon'
      preLoaderRoute: typeof ModifyhackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mergercreateportfolio': {
      id: '/mergercreateportfolio'
      path: '/mergercreateportfolio'
      fullPath: '/mergercreateportfolio'
      preLoaderRoute: typeof MergercreateportfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberselection': {
      id: '/memberselection'
      path: '/memberselection'
      fullPath: '/memberselection'
      preLoaderRoute: typeof MemberselectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathondetail': {
      id: '/hackathondetail'
      path: '/hackathondetail'
      fullPath: '/hackathondetail'
      preLoaderRoute: typeof HackathondetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon': {
      id: '/hackathon'
      path: '/hackathon'
      fullPath: '/hackathon'
      preLoaderRoute: typeof HackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createportfolio': {
      id: '/createportfolio'
      path: '/createportfolio'
      fullPath: '/createportfolio'
      preLoaderRoute: typeof CreateportfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createhackathon': {
      id: '/createhackathon'
      path: '/createhackathon'
      fullPath: '/createhackathon'
      preLoaderRoute: typeof CreatehackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/templates/$id': {
      id: '/templates/$id'
      path: '/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/messages/new': {
      id: '/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof MessagesNewRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
  MessagesNewRoute: typeof MessagesNewRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
  MessagesNewRoute: MessagesNewRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface PortfolioRouteChildren {
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesIdRoute: typeof TemplatesIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIdRoute: TemplatesIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ContestsRoute: ContestsRoute,
  CreatehackathonRoute: CreatehackathonRoute,
  CreateportfolioRoute: CreateportfolioRoute,
  HackathonRoute: HackathonRoute,
  HackathondetailRoute: HackathondetailRoute,
  LoginRoute: LoginRoute,
  MemberselectionRoute: MemberselectionRoute,
  MergercreateportfolioRoute: MergercreateportfolioRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ModifyhackathonRoute: ModifyhackathonRoute,
  ModifyportfolioRoute: ModifyportfolioRoute,
  MyRoute: MyRoute,
  MypageRoute: MypageRoute,
  MyprojectsRoute: MyprojectsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PortfoliodetailRoute: PortfoliodetailRoute,
  Portfoliodetailpage2Route: Portfoliodetailpage2Route,
  Portfoliodetailpage3Route: Portfoliodetailpage3Route,
  PortfoliopageeditorRoute: PortfoliopageeditorRoute,
  ProfileeditRoute: ProfileeditRoute,
  RecruiterRoute: RecruiterRoute,
  SignupdeveloperRoute: SignupdeveloperRoute,
  SignupdeveloperemailRoute: SignupdeveloperemailRoute,
  SignuprecruiterRoute: SignuprecruiterRoute,
  SignuprecruiteremailRoute: SignuprecruiteremailRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
